name: Documentation
on:
  push:
    branches:
      - main
      - /^release-.*$/
    tags: ['*']
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
